[package]
name = "neo4r-server"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
rdma = ["neo4r-db/rdma"]

[dependencies]
neo4r-core = { path = "../neo4r-core" }
neo4r-db = { path = "../neo4r-db" }
neo4r-protocol = { path = "../neo4r-protocol" }
neo4r-query = { path = "../neo4r-query" }
neo4r-storage = { path = "../neo4r-storage" }
rustls = { version = "=0.23.31", default-features = false, features = ["ring", "std", "tls12"] }
rustls-pemfile = "2.2.0"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
