include!("tests/database_tests_00.rs");
include!("tests/database_tests_01.rs");
include!("tests/database_tests_02.rs");
include!("tests/database_tests_03.rs");
include!("tests/database_tests_04.rs");
include!("tests/database_tests_05.rs");
include!("tests/database_tests_06.rs");
include!("tests/database_tests_07.rs");
include!("tests/database_tests_08.rs");
