use super::json_escape;

pub(crate) struct WebMetricsSnapshot {
    pub(crate) http_requests: u64,
    pub(crate) http_errors: u64,
    pub(crate) auth_failures: u64,
    pub(crate) auth_rate_limited: u64,
    pub(crate) queries: u64,
    pub(crate) query_errors: u64,
    pub(crate) slow_queries: u64,
    pub(crate) slow_query_threshold_ms: u128,
    pub(crate) registry_requests: u64,
    pub(crate) stale_epoch_rejections: u64,
    pub(crate) redirects: u64,
    pub(crate) gossip_live_nodes: usize,
    pub(crate) gossip_expired_nodes: usize,
    pub(crate) gossip_replication_negotiation_pending: usize,
    pub(crate) gossip_fanout_success: u64,
    pub(crate) gossip_fanout_failure: u64,
    pub(crate) gossip_auth_failures: u64,
    pub(crate) gossip_negotiation_success: u64,
    pub(crate) gossip_negotiation_failure: u64,
    pub(crate) migration_state: String,
    pub(crate) db_nodes: usize,
    pub(crate) db_relationships: usize,
    pub(crate) db_indexes: usize,
    pub(crate) db_vector_indexes: usize,
    pub(crate) db_shard_count: u64,
    pub(crate) db_local_partition_count: usize,
    pub(crate) db_committed_indexes: Vec<u64>,
    pub(crate) db_applied_indexes: Vec<u64>,
    pub(crate) tenant_database_count: usize,
    pub(crate) tenant_disabled_count: usize,
    pub(crate) index_ready_count: usize,
    pub(crate) index_building_count: usize,
    pub(crate) index_rebuilding_count: usize,
    pub(crate) index_failed_count: usize,
    pub(crate) raft_group_count: usize,
    pub(crate) raft_leader_count: usize,
    pub(crate) raft_term_max: u64,
    pub(crate) raft_snapshot_index_max: u64,
    pub(crate) raft_joint_consensus_count: usize,
    pub(crate) web_user_token_count: usize,
    pub(crate) web_audit_event_count: usize,
    pub(crate) replication_sent_batches: usize,
    pub(crate) replication_acked_batches: usize,
    pub(crate) replication_failed_batches: usize,
    pub(crate) replication_sent_entries: usize,
    pub(crate) replication_sent_bytes: u64,
    pub(crate) replication_in_flight_batches: usize,
    pub(crate) replication_max_in_flight_batches: usize,
    pub(crate) replication_backpressure_rejections: usize,
    pub(crate) raft_election_rounds: usize,
    pub(crate) raft_append_conflicts: usize,
    pub(crate) raft_snapshot_installs: usize,
    pub(crate) raft_snapshot_install_millis: u64,
    pub(crate) query_plan_cost_model_version: u64,
    pub(crate) backup_restore_last_success_timestamp_seconds: u64,
    pub(crate) storage_repair_last_success_timestamp_seconds: u64,
    pub(crate) storage_repair_failures: u64,
    pub(crate) slo_query_error_rate_ppm: u64,
    pub(crate) slo_latency_high_watermark_ms: u64,
    pub(crate) slo_replication_lag_entries: u64,
    pub(crate) slo_burn_rate_ppm: u64,
}

impl WebMetricsSnapshot {
    pub(crate) fn to_json(&self) -> String {
        format!(
            "{{\"http_requests\":{},\"http_errors\":{},\"auth_failures\":{},\"auth_rate_limited\":{},\"queries\":{},\"query_errors\":{},\"slow_queries\":{},\"slow_query_threshold_ms\":{},\"registry_requests\":{},\"stale_epoch_rejections\":{},\"redirects\":{},\"gossip_live_nodes\":{},\"gossip_expired_nodes\":{},\"gossip_replication_negotiation_pending\":{},\"gossip_fanout_success\":{},\"gossip_fanout_failure\":{},\"gossip_auth_failures\":{},\"gossip_negotiation_success\":{},\"gossip_negotiation_failure\":{},\"migration_state\":\"{}\",\"db_nodes\":{},\"db_relationships\":{},\"db_indexes\":{},\"db_vector_indexes\":{},\"db_shard_count\":{},\"db_local_partition_count\":{},\"db_committed_indexes\":[{}],\"db_applied_indexes\":[{}],\"tenant_database_count\":{},\"tenant_disabled_count\":{},\"index_ready_count\":{},\"index_building_count\":{},\"index_rebuilding_count\":{},\"index_failed_count\":{},\"raft_group_count\":{},\"raft_leader_count\":{},\"raft_term_max\":{},\"raft_snapshot_index_max\":{},\"raft_joint_consensus_count\":{},\"web_user_token_count\":{},\"web_audit_event_count\":{},\"replication_sent_batches\":{},\"replication_acked_batches\":{},\"replication_failed_batches\":{},\"replication_sent_entries\":{},\"replication_sent_bytes\":{},\"replication_in_flight_batches\":{},\"replication_max_in_flight_batches\":{},\"replication_backpressure_rejections\":{},\"raft_election_rounds\":{},\"raft_append_conflicts\":{},\"raft_snapshot_installs\":{},\"raft_snapshot_install_millis\":{},\"query_plan_cost_model_version\":{},\"backup_restore_last_success_timestamp_seconds\":{},\"storage_repair_last_success_timestamp_seconds\":{},\"storage_repair_failures\":{},\"slo_query_error_rate_ppm\":{},\"slo_latency_high_watermark_ms\":{},\"slo_replication_lag_entries\":{},\"slo_burn_rate_ppm\":{}}}",
            self.http_requests,
            self.http_errors,
            self.auth_failures,
            self.auth_rate_limited,
            self.queries,
            self.query_errors,
            self.slow_queries,
            self.slow_query_threshold_ms,
            self.registry_requests,
            self.stale_epoch_rejections,
            self.redirects,
            self.gossip_live_nodes,
            self.gossip_expired_nodes,
            self.gossip_replication_negotiation_pending,
            self.gossip_fanout_success,
            self.gossip_fanout_failure,
            self.gossip_auth_failures,
            self.gossip_negotiation_success,
            self.gossip_negotiation_failure,
            json_escape(&self.migration_state),
            self.db_nodes,
            self.db_relationships,
            self.db_indexes,
            self.db_vector_indexes,
            self.db_shard_count,
            self.db_local_partition_count,
            self.db_committed_indexes
                .iter()
                .map(u64::to_string)
                .collect::<Vec<_>>()
                .join(","),
            self.db_applied_indexes
                .iter()
                .map(u64::to_string)
                .collect::<Vec<_>>()
                .join(","),
            self.tenant_database_count,
            self.tenant_disabled_count,
            self.index_ready_count,
            self.index_building_count,
            self.index_rebuilding_count,
            self.index_failed_count,
            self.raft_group_count,
            self.raft_leader_count,
            self.raft_term_max,
            self.raft_snapshot_index_max,
            self.raft_joint_consensus_count,
            self.web_user_token_count,
            self.web_audit_event_count,
            self.replication_sent_batches,
            self.replication_acked_batches,
            self.replication_failed_batches,
            self.replication_sent_entries,
            self.replication_sent_bytes,
            self.replication_in_flight_batches,
            self.replication_max_in_flight_batches,
            self.replication_backpressure_rejections,
            self.raft_election_rounds,
            self.raft_append_conflicts,
            self.raft_snapshot_installs,
            self.raft_snapshot_install_millis,
            self.query_plan_cost_model_version,
            self.backup_restore_last_success_timestamp_seconds,
            self.storage_repair_last_success_timestamp_seconds,
            self.storage_repair_failures,
            self.slo_query_error_rate_ppm,
            self.slo_latency_high_watermark_ms,
            self.slo_replication_lag_entries,
            self.slo_burn_rate_ppm
        )
    }
}
